---
- name: Pull image from repository
  docker_image:
    name: mugaojoy/mugao-yolo-client:v1.0.0
    source: pull

- name: Create Node.js Backendfronted Container
  docker_container:
    name: mugao-yolo-client
    image: mugaojoy/mugao-yolo-client:v1.0.0
    networks:
      - name: weekfivenet
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes