apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service 
  labels:
    app: yolo-backend 
spec:
  type: LoadBalancer  
  selector:
    app: yolo-backend  # Matches pods with this label
  ports:
  - port: 5000  
    targetPort: 5000  # Port on the container that the service routes traffic to
    protocol: TCP  
  externalTrafficPolicy: Local  # Ensures source IPs are preserved for requests