apiVersion: v1
kind: Service
metadata:
  name: backend-deployment-joy
  labels:
    app: backend-deployment-joy  
spec:
  type: LoadBalancer  
  selector:
    app: backend-deployment-joy   
  ports:
  - port: 5000  
    targetPort: 5000  
    protocol: TCP  
  externalTrafficPolicy: Local  