apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-joy
  labels:
    app: backend-deployment-joy
  annotations:
    description: Deployment for the last IP backend application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-deployment-joy
  template:
    metadata:
      labels:
        app: backend-deployment-joy
    spec:
      containers:
      - name: backend-deployment-joy
        image: mugaojoy/mugao-yolo-backend:v1.0.0
        command: ["npm", "start"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: mugaojoy-storage
          mountPath: /app/storage
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: mugaojoy-storage
        persistentVolumeClaim:
          claimName: backend-deployment-joy-storage-claim
