apiVersion: v1
kind: Service
metadata:
  name: client-deployment-joy 
  labels:
    app: client-deployment-joy
spec:
  type: LoadBalancer  
  selector:
    app: client-deployment-joy 
  ports:
  - port: 80  
    targetPort: 80 