apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-deployment-joy-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: backend-deployment-joy-disk
    fsType: ext4
