apiVersion: v1
kind: PersistentVolume
metadata:
  name: lastip-vol
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: standard  
  gcePersistentDisk:
    pdName: lastip-pv-disk  
    fsType: ext4  