apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-deployment-joy-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
